spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_system?createDatabaseIfNotExist=true
    username: root
    password: isura1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true